export enum TransactionType {
  TRANSFER_IN = 'TRANSFER_IN',
  TRANSFER_OUT = 'TRANSFER_OUT',
  WITHDRAWAL = 'WITHDRAWAL',
  PENSION = 'PENSION',
  BONUS = 'BONUS',
  UTILITY_PAYMENT = 'UTILITY_PAYMENT',
}
